name: docker-sshd-xip

on:
  push:
    branches:
      - main
  schedule:
      - cron: '6 6 6 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 💿 Setup Docker (1/2)
      uses: docker/setup-qemu-action@v3
    - name: 💿 Setup Docker (2/2)
      uses: docker/setup-buildx-action@v3

    - name: 👤 Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 🚀 Push docker-sshd-xip
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          xipdockeruser/docker-sshd-xip:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: 🚀 Push docker-sshd-xip wiremind
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          xipdockeruser/docker-sshd-xip:wiremind
        build-args: |
          wiremind=true
        cache-from: type=gha
        cache-to: type=gha,mode=max
